---
format: gfm
---

```{r}
#| echo: false
#| eval: false
# Package setup:
usethis::use_description()
usethis::use_package("sf")
usethis::use_package("stplanr")
usethis::use_package("ggplot2")
usethis::use_package("dplyr")
usethis::use_r("opsnap")
# MIT license:
usethis::use_mit_license("Leeds Institute for Transport Studies")

# Add CI
usethis::use_github_action_check_standard()
# Add pkgdown
usethis::use_pkgdown()
# Add pkgdown action
usethis::use_github_action("pkgdown")
# Add gh pages:
usethis::use_github_pages()
```

# Installation

Install the package from GitHub:

```r
remotes::install_github("ITSLeeds/opsnap")
```

```{r}
#| include: false
library(tidyverse)
remotes::install_github("ITSLeeds/opsnap")
```

```{r}
#| eval: false
#| echo: false
devtools::load_all()
```

# Opsnap data

The `opsnap` package provides a function to download and read in data from the West Yorkshire Police Operation Snap database. The data is available at the following URL: https://www.westyorkshire.police.uk/SaferRoadsSubmissions

The data is open acess and looks like this, with names cleaned up by the package:

```{r}
u = "https://www.westyorkshire.police.uk/sites/default/files/2024-01/operation_snap_oct-dec_2023_0.xlsx"
d = opsnap:::download_and_read(u)
names(d)
# Old names:
#  [1] "REPORTER TRANSPORT MODE" "OFFENDER VEHICLE MAKE"  
#  [3] "OFFENDER VEHICLE MODEL"  "OFFENDER VEHICLE COLOUR"
#  [5] "OFFENCE"                 "DISTRICT"               
#  [7] "DISPOSAL"                "DATE OF SUBMISSION"     
#  [9] "...9"                    "OFF LOCATION"
```

```{r}
# Function to clean up column names
d_sample = d[1:50, ]
d_sf = opsnap:::op_geocode(d_sample)
mapview::mapview(d_sf)
```


```{r}
table(d$OFFENCE) |>
  sort()
```


```{r}
d |>
  # Reduce nchar of OFFENCE
  mutate(OFFENCE = stringr::str_sub(OFFENCE, 1, 60)) |>
  group_by(OFFENCE) |>
  # Count number of rows in each group
  mutate(n = n()) |>
  filter(n > nrow(d) / 50)|>
  ggplot() +
  geom_bar(aes(OFFENCE)) +
  # Make x labels vertical
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  
```